"""
data.py — Dataset builder for the Sentiment Analyzer.

Uses a hand-crafted dataset of 200 labeled sentences so the project
runs without any internet connection or extra downloads.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# ---------------------------------------------------------------------------
# Raw labeled sentences  (label: 1 = positive, 0 = negative)
# ---------------------------------------------------------------------------
_SAMPLES = [
    # --- POSITIVE ---
    ("I absolutely loved this movie, it was fantastic!", 1),
    ("This product exceeded all my expectations.", 1),
    ("What a wonderful experience, I'll definitely come back.", 1),
    ("The customer service was outstanding and very helpful.", 1),
    ("I'm so happy with my purchase, highly recommend!", 1),
    ("Brilliant performance by the entire cast.", 1),
    ("The food was delicious and the ambiance was perfect.", 1),
    ("Best book I've read in years, truly inspiring.", 1),
    ("Great quality for the price, very satisfied.", 1),
    ("The staff were friendly and professional throughout.", 1),
    ("Amazing graphics and an engaging storyline.", 1),
    ("I couldn't be more pleased with the results.", 1),
    ("Superb craftsmanship and attention to detail.", 1),
    ("This exceeded my expectations in every way.", 1),
    ("The concert was electrifying, absolutely loved it.", 1),
    ("Wonderful atmosphere and excellent service.", 1),
    ("I'm thrilled with how this turned out.", 1),
    ("The app is intuitive and works flawlessly.", 1),
    ("Phenomenal acting and a gripping plot.", 1),
    ("Best vacation I've ever had, unforgettable memories.", 1),
    ("Really enjoyed the presentation, very informative.", 1),
    ("The packaging was beautiful and the product is perfect.", 1),
    ("Outstanding value, will buy again without hesitation.", 1),
    ("I feel so energised and refreshed after this experience.", 1),
    ("The team did an incredible job under pressure.", 1),
    ("Delightful read, couldn't put it down.", 1),
    ("Impressive range of features for the price.", 1),
    ("The hotel was immaculate and the staff impeccable.", 1),
    ("Loved every minute of it, pure joy.", 1),
    ("This is exactly what I was looking for.", 1),
    ("Very comfortable and stylish, great buy.", 1),
    ("Exceeded my high expectations, truly remarkable.", 1),
    ("The flavours were exquisite and perfectly balanced.", 1),
    ("Excellent tutorial, clear and easy to follow.", 1),
    ("I had a fantastic time from start to finish.", 1),
    ("The build quality is exceptional, very impressed.", 1),
    ("Smooth delivery and the item was well packaged.", 1),
    ("Absolutely brilliant, I cannot fault it.", 1),
    ("The kids loved it, big smiles all around.", 1),
    ("Top-notch support team, resolved my issue instantly.", 1),
    ("Gorgeous design and works exactly as described.", 1),
    ("The experience left me feeling uplifted and inspired.", 1),
    ("Effortless setup and performs beautifully.", 1),
    ("One of the best decisions I've ever made.", 1),
    ("The workshop was engaging, practical, and fun.", 1),
    ("I'm genuinely impressed by the quality.", 1),
    ("Received compliments from everyone who saw it.", 1),
    ("The course content was rich and well-structured.", 1),
    ("Highly professional and delivered ahead of schedule.", 1),
    ("An absolute gem, I recommend it to everyone.", 1),
    ("Felt welcomed from the moment I walked in.", 1),
    ("The results speak for themselves — outstanding.", 1),
    ("Crisp, clear, and beautifully designed interface.", 1),
    ("Really glad I gave this a try, won't regret it.", 1),
    ("The speaker was engaging and knowledgeable.", 1),
    ("Five stars without hesitation.", 1),
    ("Worth every penny and more.", 1),
    ("Remarkable improvement after just a few days of use.", 1),
    ("The storytelling was captivating and emotionally rich.", 1),
    ("Felt like a luxury experience at an affordable price.", 1),
    ("Everything worked perfectly straight out of the box.", 1),
    ("The scenery was breathtaking and the guide fantastic.", 1),
    ("Incredibly fast shipping and excellent product.", 1),
    ("The soundtrack was hauntingly beautiful.", 1),
    ("Simple to use and surprisingly powerful.", 1),
    ("The design is sleek and feels premium.", 1),
    ("I woke up smiling just thinking about it.", 1),
    ("Hands down the best purchase of the year.", 1),
    ("The demo blew me away — can't wait to get started.", 1),
    ("Warm, welcoming, and wonderfully executed.", 1),
    ("Polished, professional, and genuinely useful.", 1),
    ("My whole family enjoyed it thoroughly.", 1),
    ("The attention to detail is second to none.", 1),
    ("Left feeling motivated and full of new ideas.", 1),
    ("Charming, witty, and thoroughly entertaining.", 1),
    ("A seamless experience from beginning to end.", 1),
    ("The upgrade was well worth it, night and day difference.", 1),
    ("Beautiful presentation and flawless execution.", 1),
    ("Blew past my expectations — absolutely delighted.", 1),
    ("Such a thoughtful gift, perfectly chosen.", 1),
    ("The flavour hit every note I hoped for.", 1),
    ("I'm recommending this to all my friends immediately.", 1),
    ("The platform is fast, reliable, and a pleasure to use.", 1),
    ("Everything about this experience was top tier.", 1),
    ("Loved the creativity and originality on display.", 1),
    ("It genuinely made my life easier — no exaggeration.", 1),
    ("The repair was swift, tidy, and reasonably priced.", 1),
    ("I smiled the whole way through — pure delight.", 1),
    ("Elegant solution to a tricky problem.", 1),
    ("Incredibly responsive and helpful from day one.", 1),
    ("Felt like the product was designed just for me.", 1),
    ("Ticked every box and then some.", 1),
    ("The experience was transformative in the best way.", 1),
    ("Stood up to heavy use without a single complaint.", 1),
    ("Even better in person than in the photos.", 1),
    ("The results were immediate and impressive.", 1),
    ("Thoroughly tested and works without a hitch.", 1),
    ("Generous portions and outstanding taste.", 1),
    ("The class was inspiring and the instructor superb.", 1),
    ("Couldn't ask for a better outcome — very happy.", 1),
    # --- NEGATIVE ---
    ("This was a complete waste of money and time.", 0),
    ("Terrible quality, broke after one day of use.", 0),
    ("The worst customer service I have ever experienced.", 0),
    ("I'm extremely disappointed with this product.", 0),
    ("Absolutely horrible, would not recommend to anyone.", 0),
    ("The food was cold, tasteless, and overpriced.", 0),
    ("Nothing worked as advertised, total scam.", 0),
    ("Rude staff and a filthy environment.", 0),
    ("The movie was painfully boring and poorly acted.", 0),
    ("I regret buying this, complete rubbish.", 0),
    ("Shocking experience, I will never return.", 0),
    ("The product arrived damaged and support ignored me.", 0),
    ("Dreadful quality and the instructions were useless.", 0),
    ("Waited three weeks and still haven't received my order.", 0),
    ("The app crashes every five minutes, infuriating.", 0),
    ("False advertising — nothing like what was shown.", 0),
    ("A total disappointment from start to finish.", 0),
    ("The concert was disorganised and the sound awful.", 0),
    ("I've never felt so let down by a brand before.", 0),
    ("Poor performance and overheats within minutes.", 0),
    ("The hotel room was dirty and smelled terrible.", 0),
    ("Completely unusable, a waste of shelf space.", 0),
    ("The seams came apart after the first wash.", 0),
    ("No response from customer service for two weeks.", 0),
    ("The battery dies within an hour of charging.", 0),
    ("Overcrowded, understaffed, and badly managed.", 0),
    ("The presentation was incoherent and poorly prepared.", 0),
    ("Cheap materials that feel flimsy and unsafe.", 0),
    ("Extremely slow delivery with zero communication.", 0),
    ("The plot made no sense and the ending was awful.", 0),
    ("I'm furious — this is not what I paid for.", 0),
    ("The noise level was unbearable throughout the stay.", 0),
    ("Completely misrepresented in the product description.", 0),
    ("The worst meal I have ever had, inedible.", 0),
    ("Setup took hours and nothing worked in the end.", 0),
    ("The refund process was a nightmare, avoid at all costs.", 0),
    ("Pathetic quality control, full of defects.", 0),
    ("The guide was unhelpful and spoke over everyone.", 0),
    ("Broke down on the first use, shocking.", 0),
    ("The subscription is impossible to cancel, disgusting.", 0),
    ("I wasted my entire evening on this rubbish.", 0),
    ("Uncomfortable, impractical, and poorly made.", 0),
    ("The interface is confusing and full of bugs.", 0),
    ("Took my money and delivered nothing.", 0),
    ("I'm appalled by the lack of care shown.", 0),
    ("The reviews must be fake — this is awful.", 0),
    ("Cheap knock-off, not the genuine product at all.", 0),
    ("The speakers were tinny and the picture blurry.", 0),
    ("Terrible experience that ruined my whole day.", 0),
    ("I left the restaurant hungry and angry.", 0),
    ("The item is nothing like the pictures shown.", 0),
    ("Deeply unsatisfied and I want a full refund.", 0),
    ("Absolute junk, falls apart at the slightest touch.", 0),
    ("The service was painfully slow and the staff indifferent.", 0),
    ("Not fit for purpose and dangerously flimsy.", 0),
    ("Riddled with errors and impossible to follow.", 0),
    ("The worst investment I've made in a long time.", 0),
    ("Zero stars if I could — thoroughly unimpressed.", 0),
    ("The smell was off-putting from the moment I opened it.", 0),
    ("Ripped off — the price is outrageous for this quality.", 0),
    ("The class was a chaotic, unplanned disaster.", 0),
    ("Couldn't connect it to anything, utterly pointless.", 0),
    ("Arrived weeks late and in the wrong colour.", 0),
    ("The plot holes were glaring and the dialogue cringe-worthy.", 0),
    ("I'm embarrassed I recommended this to a friend.", 0),
    ("The machine jammed on the very first use.", 0),
    ("Terrible value and zero customer aftercare.", 0),
    ("The fabric shrunk dramatically after one wash.", 0),
    ("Endlessly frustrating and not user-friendly at all.", 0),
    ("Hidden charges I was never told about — disgraceful.", 0),
    ("The tour was rushed, disorganised, and deeply disappointing.", 0),
    ("Completely unreliable and let me down when I needed it most.", 0),
    ("I feel cheated and will be seeking a refund.", 0),
    ("The manual is incomprehensible and the product defective.", 0),
    ("Loud, cheap, and ineffective — avoid completely.", 0),
    ("The coating peeled off after two days of light use.", 0),
    ("Unacceptable delays with no apology or explanation.", 0),
    ("Broke mid-task and caused me to lose hours of work.", 0),
    ("The whole experience was stressful and unsatisfactory.", 0),
    ("I cannot believe this passed any quality check.", 0),
    ("Woefully inadequate and a complete waste of resources.", 0),
    ("The staff were dismissive and made me feel unwelcome.", 0),
    ("It looked nothing like the advertisement — misleading.", 0),
    ("The instructions contradicted themselves at every step.", 0),
    ("Extremely noisy and disturbed everyone around me.", 0),
    ("I returned it immediately — completely unacceptable.", 0),
    ("The packaging was fine but the product inside was broken.", 0),
    ("Doesn't deliver on a single promise made in the listing.", 0),
    ("Chronic delays and an indifferent support team.", 0),
    ("The screen flickered constantly — unwatchable.", 0),
    ("The worst service I have encountered in years.", 0),
    ("The event was poorly attended because of bad organisation.", 0),
    ("Left with a headache from the experience.", 0),
    ("I'm still waiting for an apology, let alone a fix.", 0),
    ("The quality declined sharply since the last version.", 0),
    ("Flimsy construction and amateurish finish throughout.", 0),
    ("The portions were tiny and the flavour nonexistent.", 0),
    ("I had high hopes but was thoroughly let down.", 0),
    ("Riddled with glitches and freezes every few minutes.", 0),
    ("The checkout process was a confusing, broken mess.", 0),
    ("One star is far too generous for this disaster.", 0),
]


def load_dataset() -> pd.DataFrame:
    """Return a DataFrame with columns: text, label."""
    df = pd.DataFrame(_SAMPLES, columns=["text", "label"])
    df = df.sample(frac=1, random_state=42).reset_index(drop=True)
    return df


def get_splits(test_size: float = 0.2, random_state: int = 42):
    """Return (X_train, X_test, y_train, y_test) as Series / arrays."""
    df = load_dataset()
    X = df["text"]
    y = df["label"]
    return train_test_split(X, y, test_size=test_size,
                            random_state=random_state, stratify=y)


if __name__ == "__main__":
    df = load_dataset()
    print(f"Dataset shape : {df.shape}")
    print(f"Label balance :\n{df['label'].value_counts()}")
    print("\nSample rows:")
    print(df.head(4).to_string(index=False))
